trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Set up Python 3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo Running Payroll.py
      if not exist payslips mkdir payslips
      if not exist logs mkdir logs
      if not exist output mkdir output
      python Payroll.py
    displayName: 'Run Payroll App'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Summary'
    inputs:
      PathtoPublish: 'output'
      ArtifactName: 'Summary'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Payslips'
    inputs:
      PathtoPublish: 'payslips'
      ArtifactName: 'Payslips'
      publishLocation: 'Container'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish Logs'
    inputs:
      PathtoPublish: 'logs'
      ArtifactName: 'Logs'
      publishLocation: 'Container'
