trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Set up Python 3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      mkdir -p output
      python Payroll_from_db.py
    displayName: 'Run Payroll App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'output'
      ArtifactName: 'PayrollArtifacts'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'