trigger:
  - main

pool:
  vmImage: 'windows-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.10'
    displayName: 'Set up Python 3.10'

  - script: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    displayName: 'Install dependencies'

  - script: |
      echo Running Payroll.py
      if not exist output mkdir output
      python Payroll.py
    displayName: 'Debug Payroll App'

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'output'
      ArtifactName: 'PayrollArtifacts'
      publishLocation: 'Container'
    displayName: 'Publish Artifacts'

  - task: PublishBuildArtifacts@2
  inputs:
    PathtoPublish: 'payroll_error.log'
    ArtifactName: 'ErrorLog'
  condition: failed()

